import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('http://localhost:4200/');
    await page.goto('http://localhost:4200/home');
    await expect(page.locator('a')).toContainText('Answerz');
    await page.getByRole('button', { name: 'S\'inscrire' }).click();
    await page.getByLabel('Prénom').click();
    await page.getByLabel('Prénom').fill('testPrénom');
    await page.getByLabel('Prénom').press('Tab');
    await page.getByLabel('Nom', { exact: true }).fill('testNom');
    await page.getByLabel('Nom', { exact: true }).press('Tab');
    await page.getByLabel('Nom d\'utilisateur').fill('testPseudo');
    await page.getByLabel('Nom d\'utilisateur').press('Tab');
    await page.getByLabel('Email').click();
    await page.getByLabel('Email').fill('testPrenom.testNom@gmail.com');
    await page.getByLabel('Email').press('Tab');
    await page.getByLabel('Mot de passe', { exact: true }).fill('password1234');
    await page.getByLabel('Mot de passe', { exact: true }).press('Tab');
    await page.getByLabel('Confirmer le mot de passe').fill('password1234');
    await page.goto('http://localhost:4200/home');
    await page.locator('form').getByRole('button', { name: 'S\'inscrire' }).click();
    await expect(page.locator('app-index')).toContainText('S\'amuser tout en apprenant avec AnswerZ');
    await page.locator('p-avatar').getByRole('img').click();
    await page.getByLabel('Déconnexion').locator('a').click();
    await page.getByLabel('E-mail').click();
    await page.getByLabel('E-mail').fill('testPrenom.testNom@gmail.com');
    await page.getByLabel('E-mail').press('Tab');
    await page.getByLabel('Mot de passe').fill('password1234');
    await page.locator('form').getByRole('button', { name: 'Se connecter' }).click();
    await expect(page.locator('app-index')).toContainText('Une application gratuite pour tous');
    await page.getByRole('button', { name: 'Flashcards' }).click();
    await page.getByRole('button', { name: '' }).click();
    await page.locator('p-dropdown').filter({ hasText: 'CATEGORIES' }).getByLabel('dropdown trigger').click();
    await page.getByLabel('English').click();
    await expect(page.locator('#pn_id_8_label')).toContainText('English');
    await page.getByPlaceholder('Name').click();
    await page.getByPlaceholder('Name').fill('Nom');
    await page.getByPlaceholder('Name').press('Tab');
    await page.getByPlaceholder('Description').fill('Description');
    await page.getByRole('button', { name: 'CREATE YOUR SET' }).click();
    await page.getByPlaceholder('Question').click();
    await page.getByPlaceholder('Question').fill('Question 1');
    await page.getByPlaceholder('Question').press('Tab');
    await page.getByPlaceholder('Answer').fill('Question 2');
    await page.getByRole('button', { name: 'ADD FLASHCARD TO SET' }).click();
    await expect(page.locator('#previewSection div').filter({ hasText: 'Flashcard #1.......................................................QuestionQuestion 1AnswerQuestion' }).first()).toBeVisible();
    await page.getByRole('button', { name: 'SAVE YOUR FLASHCARD SET' }).click();
    await page.getByLabel('dropdown trigger').click();
    await page.getByLabel('Public').click();
    await expect(page.locator('[id="\\35 "]')).toBeVisible();
    await page.locator('p-avatar').getByRole('img').click();
    await page.getByLabel('Mon profil').locator('a').click();
    await expect(page.locator('app-user-profile')).toContainText('testPrénom testNom');
    await expect(page.locator('h1')).toContainText('Mon profil');
    await page.getByRole('button', { name: 'Éditer' }).click();
    await page.getByLabel('dropdown trigger').click();
    await page.getByText('English').click();
    await page.getByRole('button', { name: 'Sauvegarder' }).click();
    await expect(page.locator('h1')).toContainText('My profile');
    await page.getByLabel('dropdown trigger').click();
    await page.getByLabel('Français').click();
    await page.getByRole('button', { name: 'Save' }).click();
    await expect(page.locator('h1')).toContainText('Mon profil');
    await page.locator('app-header p-avatar').getByRole('img').click();
    await page.getByLabel('Déconnexion').locator('a').click();
});